
project_id = "gswwmieyrfdhrfwsgjnw"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
uri = "http://127.0.0.1:54321/auth/v1"

[functions.jira-api]
verify_jwt = false

[functions.chat-with-jira]
verify_jwt = false

[functions.save-story-artifacts]
verify_jwt = false

[functions.save-context]
verify_jwt = false

[functions.process-document]
verify_jwt = false

[functions.query-documents]
verify_jwt = false

