
project_id = "gswwmieyrfdhrfwsgjnw"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[functions.chat-with-data-model]
verify_jwt = false

[functions.chat-with-documents]
verify_jwt = false

[functions.chat-with-all-project-data]
verify_jwt = false
